dataset: CIFAR10
n_classes_per_phase: 2
n_phases: 5
other: true
shared_memory_size: 0
clf_memory_size: 350
ctrl_memory_size: 150
clf:
  epochs: 50
  epochs_tol: 20
  lr: 0.01
  lr_scheduler: poly1
  min_lr: 1.0e-05
  update_epochs: 50
  update_epochs_tol: 4
ctrl:
  epochs: 200
  epochs_tol: 20
  hidden_activation: Sigmoid
  hidden_layer_scale: 0.0
  lr: 0.01
  lr_scheduler: poly1
  min_lr: 1.0e-05
  pos: after
lr_decay: 0.25
lr_patience: 3
val_size: 0.2
balance_other_classsize: true
balance_other_samplesize: true
clone_head: false
pretrained: 'simple_net_20_classes'
split_pos: 10
batch_size: 16
class_order_seed: -1
weight_decay: 1.0e-05
update_classifiers: false
update_scores: false
datadir: ../data
logdir: ./logs
download: false
resize_input: null
num_workers: 2