dataset: CIFAR10
n_classes_per_phase: 2
n_phases: 5
other: true
memory_size: 500
clf:
  epochs: 50
  epochs_tol: 4
  lr: 0.01
  lr_scheduler: poly1
  min_lr: 1.0e-05
  update_epochs: 50
  update_epochs_tol: 4
ctrl:
  epochs: 20
  epochs_tol: 4
  hidden_activation: Sigmoid
  hidden_layer_scale: 0.0
  lr: 0.01
  lr_scheduler: poly1
  memory_size: 0
  min_lr: 1.0e-05
  pos: after
lr_decay: 0.25
lr_patience: 3
val_size: 0.2
balance_other_classsize: true
balance_other_samplesize: true
clone_head: false
pretrained: exp2/simple_net.pty
split_pos: 10
batch_size: 16
class_order_seed: -1
weight_decay: 1.0e-05
update_classifiers: false
update_scores: false
datadir: ../data/
logdir: ./logs/
download: false
