dataset: CIFAR10
n_classes_per_phase: 2
n_phases: 5
other: true
memory_size: 500
epochs: 50
epochs_tol: 20
lr: 0.01
lr_scheduler: exp
min_lr: 1.0e-05
optimizer: SGD
lam: 1.
gamma: 0.95
lr_patience: 3
lr_step_size: 1
val_size: 0.2
pretrained: 'simple_net_20_classes'
split_pos: 10
split_pos_lower: null
batch_size: 32
batch_memory_samples: 16
ctrl_balance_classes: false
ctrl_activation: softmax
ctrl_linear_layer: true
clf_balance_classes: false
class_order_seed: -1
weight_decay: 1.0e-05
datadir: ../data
logdir: ./logs
download: false
resize_input: null
torch:
  num_workers: 3
  pin_memory: false
  non_blocking: true
  drop_last: false
input_size: [ 3, 32, 32 ]
warmup_epochs: 1
ctrl_bias: true
warmup_level: 2
bic: true
bic_lr: 0.001
bic_epochs: 10
update_classifiers: true