dataset: CIFAR100
n_phases: 10
n_classes_per_phase: 10
memory_size: 2000
val_size: 0.2
batch_size: 128
epochs: 100
lr: 0.001
model: "efficientnet-b0"
resize_input: 224
download: true
torch:
  num_workers: 3
  pin_memory: false
datadir: ../data
class_order_seed: -1
lr_step_size: 5