dataset: TinyCIFAR10
lr: 0.01
lr_scheduler: exp
gamma: 0.95
n_phases: 5
n_classes_per_phase: 2
epochs: 20
class_order_seed: 1
memory_size: 200
torch:
  num_workers: 0
  drop_last: true
split_pos: -7
split_pos_lower: null
balance_classes: false
warmup_epochs: .inf
ctrl_bias: false
warmup_level: 2
bic_lr: 0.01