dataset: TinyCIFAR10
lr_scheduler: exp
gamma: 0.95
lr_patience: 3
n_phases: 5
n_classes_per_phase: 2
epochs: 40
class_order_seed: 1
memory_size: 200
torch:
  num_workers: 0
  drop_last: true
split_pos: -7
split_pos_lower: null
ctrl_balance_classes: false
clf_balance_classes: false
warmup_epochs: .inf
ctrl_bias: false
warmup_level: 2
bic: true
bic_lr: 0.1
lam: 0.
lr: 0.01
val_size: 0.2
other: false
ctrl_activation: sigmoid
ctrl_linear_layer: true
update_classifiers: true